#!/usr/local/bin/perl
# dbcreate.pl -- Groovy-Chatter MySQL Database Setup Script 
# Copyright (C) 1997, 1998, 1999, 2000 
# Christopher T. Kennedy <getdown@groovy.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#############################################################################


################################
#   User Directory DB Creator  #
################################

use DBI;
push (@INC,`pwd`);
require 'tools.cfg' ||
        die "The Configuration File Could Not Be Found: $!\n";

print "\nConnecting to $database on $host...";
$dbh=DBI->connect("DBI:mysql:$database:$host", $username, $password) || 
	die "Can't connect to $database on $host:\n$DBI::errstr\n";
print "\n";

print "\nCreating table $table on $host...";
$dbh->do("drop table $table");
$dbh->do("create table $table(month char(2), day char(2), hour char(2), min char(2), sec char(2), url char(30), size char(2), color char(8), hurl char(30), name char(25), passwd char(16), body char(255), number char(16), main char(100))") or die $dbh::errstr;
print "\n";

print "\nDisconnecting from $database on $host\n\n";
$dbh->disconnect;
